### PR TITLE
1.6

### PR DESCRIPTION
**Pull request by SayantanBhattacharyya**
Author: SAYANTAN BHATTACHARYYA (saybhatt) <saybhatt@cisco.com>  2016-03-01 00:15:24
Committer: SAYANTAN BHATTACHARYYA (saybhatt) <saybhatt@cisco.com>  2016-03-01 00:15:24
Parent: 749e49fec0f8d2174e9e69e55d5f276066d36ceb (logger: new HAVE_SPLICE check)
Branch: 1.6
Follows: v1.6.8
Precedes: 

    Issue seen with chrome & firefox browsers while using FCGI plugin:
    Sometimes content length is coming as ZERO and we are encoding a
    HTTP response packet with ZERO size data. This makes chrome & firefox
    browsers fail to proceed furhter and subsequent content loading fails.
    However, IE/safari discards the packets with ZERO size data.

------------------------ plugins/fastcgi/fcgi_handler.c ------------------------
index 5334270..36c2c92 100644
@@ -647,7 +647,21 @@ int cb_fastcgi_on_read(void *data)
         case FCGI_STDOUT:
             MK_TRACE("[fastcgi=%i] FCGI_STDOUT content_length=%i",
                      handler->server_fd, header.content_length);
-            ret = fcgi_response(handler, body, header.content_length);
+            /*
+             * Issue seen with chrome & firefox browsers:
+             * Sometimes content length is coming as ZERO and we are encoding a
+             * HTTP response packet with ZERO size data. This makes chrome & firefox
+             * browsers fail to proceed furhter and subsequent content loading fails.
+             * However, IE/safari discards the packets with ZERO size data.
+             */
+            if (0 != header.content_length) {
+                ret = fcgi_response(handler, body, header.content_length);
+            }
+            else {
+                MK_TRACE("[fastcgi=%i] ZERO byte content length in FCGI_STDOUT, discard!!",
+                         handler->server_fd);
+                ret = 0;
+            }
             break;
         case FCGI_STDERR:
             MK_TRACE("[fastcgi=%i] FCGI_STDERR content_length=%i",

### CODE REVIEW

**Comment by edsiper** [comment]
thanks for your contribution, some comments:

- I cannot accept this pull request as it's unreadable. It include like a hundred of commits I did my self during the last time, instead you should do a clean fork of the latest 1.6 branch and commit your changes, then submit that only change as a pull request.
- For specific notes about contribution and guidelines please check: https://github.com/monkey/monkey/blob/master/CONTRIBUTING.md

If you submit a clean PR I will be happy to merge it. Feel free to send any question you may have.

**Comment by SayantanBhattacharyya** [comment]
Hi Eduardo,

I created a new branch 1.6_FcgiFix from latest 1.6 and checked in my change
in that branch. But while creating the new pull request somehow I don't see
the branch name in git webpage. Any idea what would have happened?

Thanks & Regards,
Sayantan

**Comment by edsiper** [comment]
Looks like you don't fork it on github, go to github.com/monkey/monkey and click in the "fork" button, then you clone in your local machine your github.com/SayantanBhattacharyya/monkey repo, checkout the branch, do the changes, commit and push to your own repo. Then from your own forked repo (github.com/SayantanBhattacharyya/monkey) you issue the Pull Request

**Comment by edsiper** [comment]
Not merging. Applied patch manually: https://github.com/monkey/monkey/commit/5bf9164ca188f1fa9fdb1e8aeff425b9e3616192

**Pull request closed without merging**
