### PR TITLE
Issue 170 implemented : Syslog functional and optional

### PR DESCRIPTION
**Pull request by pfrcks**
Syslog has been implemented and can be made to work using the --enable-syslog option during configuration.
This option defines Syslog in mk_info.h file which in turn is read by logger.c
Now based on whether the option is set or not, logger.c decided whether to log to syslog or to the log files()

At present logger facility on master is broken so Syslog will not work even though it has been implemented. As soon as logger is fixed it will start working too.
Syslog utilizes syslog.h header file and logs to /var/log/syslog

### CODE REVIEW

**Comment by edsiper** [comment]
this patch will not work because of the following reasons:

- you have forced the inclusion of syslog.h 
- syslog support is optional, but logger using syslog or default file system files through a configuration file is a must
- on the commit you are including changes from files which should not be there (jemalloc, mk_static_plugins.h, etc). Commit only relevant file changes.
- in logger.c you perform two consecutive  lseek(flog, 0, SEEK_END);

you have to review your commits before to send a PR.

**Comment by pfrcks** [comment]
Okay. I'll work on the corrections.
But what do you mean by "logger using syslog or default file system files through a configuration file is a must". Do you mean that the choice has to be implemented through config of logger file rather than the main configure file?

**Comment by edsiper** [comment]
despites it was build with syslog support, a configuration file should say which mechanism should be used.

**Comment by edsiper** [comment]
Closing as not applicable.

**Pull request closed without merging**
