### PR TITLE
core: epoll: retry epoll_wait when errno == EINTR

### PR DESCRIPTION
**Pull request by nokute78**
Fluent-bit uses monkey as a library.
https://github.com/bottlerocket-os/bottlerocket/issues/1628#issuecomment-870681004 reported epoll_wait and EINTR issue.
(Also reported https://github.com/fluent/fluent-bit/issues/4063 and https://github.com/fluent/fluent-bit/issues/3521)

I sent a patch to retry epoll_wait when errno is EINTR.

FYI: golang also retries when errno is EINTR.
https://github.com/golang/go/blob/d7c073ecbfc3ecc506bfc753b271973b47f8bc15/src/runtime/netpoll_epoll.go#L119

### CODE REVIEW

**Comment by leonardo-albertovich** [comment]
I'm not completely sure of how would this change the dynamic of the client functions for the better without making an assumption that may or may not be acceptable.

The way I see it is this : 

- fluent-bit uses `mk_event_wait` and `mk_event_foreach` in `flb_engine_start` and `output_thread`
- none of these functions verify the result code of `mk_event_wait`
- `mk_event_foreach` iterates comparing to `n_events` which is signed and at least in this case wouldn't cause a problem
- in fluent-bit these function calls are made in a busy loop where they are invoked and then some cleanup functions are called which means if `epoll` failed and returned -1 in one cycle, it would probably work in the next one

I'm sure that properly handling the underlying error code is the right thing to do, what I'd like to know better is : 

1. how is this handled in the other backends?
2. are we OK with the fact that this function will block in that particular way which would be "new" to the codebase?
3. do we want to update the other backends to have a consistent behavior?
4. does this change solve those issues that are linked? (I glanced over the first one and it didn't seem that way)

**Comment by nokute78** [comment]
Thank you for comment.

> 4. does this change solve those issues that are linked? (I glanced over the first one and it didn't seem that way)

I can't reproduce issue, so I don't check if this patch can fix the issue...

BTW, below trace is about `mk_server_worker_loop` since below data `"\0\0\356\377\0\0\0\0"` is `MK_SCHED_SIGNAL_FREE_ALL         0xFFEE0000` in octal. 
It may indicate that signal cancels a loop of `mk_lib_worker` since MK_SCHED_SIGNAL_FREE_ALL will be sent if the loop is broken.

https://github.com/bottlerocket-os/bottlerocket/issues/1628#issuecomment-870681004
```
[pid  5747] 21:36:57 epoll_wait(27,  <unfinished ...>
[pid  5747] 21:36:57 <... epoll_wait resumed> 0x7f750f20c000, 256, -1) = -1 EINTR (Interrupted system call)
[pid  5747] 21:36:57 epoll_wait(27,  <unfinished ...>
[pid  5747] 21:36:57 <... epoll_wait resumed> [{EPOLLIN, {u32=253976576, u64=140140741877760}}], 256, -1) = 1
[pid  5745] 21:36:57 futex(0x7f750fffe9d0, FUTEX_WAIT, 5747, NULL <unfinished ...>
[pid  5747] 21:36:57 read(28, "\0\0\356\377\0\0\0\0", 8) = 8
```


> 1. how is this handled in the other backends?
> 3. do we want to update the other backends to have a consistent behavior?

select is needed to handle EINTR.
https://man7.org/linux/man-pages/man2/select.2.html

kqueue is not canceled by signal.
https://man.openbsd.org/kqueue.2#ERRORS

**Comment by nokute78** [comment]
User tested my local repo which is v1.8.7+this patch.
It didn't fix "stuck after few minutes" issue.
https://github.com/fluent/fluent-bit/issues/4063#issuecomment-944328693

However it may help to fix "http_server stops listening almost after start " issue.
The patch is to prevent canceling by signal at `mk_lib_worker`.
https://github.com/fluent/fluent-bit/issues/3521

**Comment by nokute78** [comment]
@leonardo-albertovich Ping.

I think signal cancels `epoll_wait` and breaks below loop since `loop->n_events = -1` and there is no retrying.
https://github.com/fluent/fluent-bit/blob/v1.8.9/lib/monkey/mk_server/mk_lib.c#L155
Then http server exits and causes https://github.com/fluent/fluent-bit/issues/3521

**Comment by leonardo-albertovich** [comment]
Coincidentally that's something I'm working on for a windows related issue @nokute78, I might be wrong but from what I could find `mk_lib_worker` calls `mk_server_loop` which calls `mk_server_loop_balancer` (because the reuseport code path is empty and we're not sure if that's a regression or what exactly) but the end result if you read the code for `mk_server_loop_balancer` is that that function never returns, it doesn't have code to handle a termination request or anything alike.

I could be wrong but it's an interesting coincidence since I'm about to submit a PR to add that mechanism to that function so if you have some thoughts on it just let me know, I'd love to discuss it further.

**Comment by nokute78** [comment]
I pushed https://github.com/nokute78/fluent-bit/tree/v1.8.12_sig_cancel for pseudo reproduction.
It is v1.8.12 + a patch https://github.com/nokute78/fluent-bit/commit/b59671205234cea04b1ce4b0d2f4aa156f89cd4a .

The patch means `epoll_wait` of `mk_lib_worker` is canceled by signal.

## How to reproduce

1. `fluent-bit -i cpu -o stdout -H &`
2. `curl localhost:2020`

Fluent-bit stopped listening port 2020 since signal cancels `epoll_wait` of `mk_lib_worker`.
```
$ curl localhost:2020
curl: (7) Failed to connect to localhost port 2020: Connection refused
```

```
$ bin/fluent-bit -i cpu -o stdout -H
Fluent Bit v1.8.12
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2022/01/30 19:39:18] [ info] [engine] started (pid=112940)
[2022/01/30 19:39:18] [ info] [storage] version=1.1.5, initializing...
[2022/01/30 19:39:18] [ info] [storage] in-memory
[2022/01/30 19:39:18] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2022/01/30 19:39:18] [ info] [cmetrics] version=0.2.2
[2022/01/30 19:39:18] [ info] [http_server] listen iface=0.0.0.0 tcp_port=2020
[2022/01/30 19:39:18] [ info] [sp] stream processor started
mk_lib_worker:canceled
[0] cpu.0: [1643539159.164866175, {"cpu_p"=>5.000000, "user_p"=>4.000000, "system_p"=>1.000000, "cpu0.p_cpu"=>5.000000, "cpu0.p_user"=>4.000000, "cpu0.p_system"=>1.000000}]
[1] cpu.0: [1643539160.164899924, {"cpu_p"=>4.000000, "user_p"=>4.000000, "system_p"=>0.000000, "cpu0.p_cpu"=>4.000000, "cpu0.p_user"=>4.000000, "cpu0.p_system"=>0.000000}]
[2] cpu.0: [1643539161.165113860, {"cpu_p"=>1.000000, "user_p"=>1.000000, "system_p"=>0.000000, "cpu0.p_cpu"=>1.000000, "cpu0.p_user"=>1.000000, "cpu0.p_system"=>0.000000}]
[3] cpu.0: [1643539162.165577155, {"cpu_p"=>2.000000, "user_p"=>2.000000, "system_p"=>0.000000, "cpu0.p_cpu"=>2.000000, "cpu0.p_user"=>2.000000, "cpu0.p_system"=>0.000000}]
^C[2022/01/30 19:39:23] [engine] caught signal (SIGINT)
[2022/01/30 19:39:23] [ info] [input] pausing cpu.0
[0] cpu.0: [1643539163.165321649, {"cpu_p"=>1.000000, "user_p"=>0.000000, "system_p"=>1.000000, "cpu0.p_cpu"=>1.000000, "cpu0.p_user"=>0.000000, "cpu0.p_system"=>1.000000}]
[2022/01/30 19:39:23] [ warn] [engine] service will shutdown in max 5 seconds
[2022/01/30 19:39:24] [ info] [engine] service has stopped (0 pending tasks)
```

**Comment by nokute78** [comment]
@leonardo-albertovich @edsiper User confirmed this patch fixed the issue https://github.com/fluent/fluent-bit/issues/3521#issuecomment-1032641646.
Could you review this patch ?

**Comment by leonardo-albertovich** [comment]
I'm not a fan of this since the function consuming the event loop results should retry (they do run in an "infinite" loop at least in fluent-bit) but if it works I think we can merge it. Should I @edsiper?

**Comment by edsiper** [comment]
if it works all good, yes please

**Comment by leonardo-albertovich** [comment]
Thank you very much @nokute78.

**Pull request merged**
