### PR TITLE
Patch allows monkey to run on FreeBSD and Linux using Kqueue

### PR DESCRIPTION
**Pull request by sujayraaj**
Three files changed. One in liana.c that makes it use the freebsd sendfile.  Other in mk_event_kqueue.c that corrects the pointer errors. And third, in mk_file.h , because freebsd was showing a compiler error without time.h. 
Regards.

### CODE REVIEW

**Comment by edsiper** [comment]
Comments:

- As each fix belongs to different parts, please submit multiple commits:
 -  mk_server: file: fix ...
 -  mk_core: kqueue: handling for netbsd...
 -  liana: fix...

questions:

1. would not be enough with "event->mask = events" ?, _data_ and _events_ should reference the  the same address.

2. why time.h is required for mk_file.c ?

**Comment by sujayraaj** [comment]
1. It should be enough. Even I think that, and I am surprised with it. The
only supporting argument I can give in its favor at the moment is that it
gets it to execute using kqueue on both systems.

2. time.h is required for mk_file.h because the 'struct file_info' declared
in mk_file.h has a member 'time_t last_modification' . It compiled well on
linux, but on freebsd it gave an error unknown type name time_t.

3. I will add commits file by file.

**Comment by edsiper** [comment]
thanks, please make sure to use the latest from GIT (I pushed some changes early this morning)

**Comment by edsiper** [comment]
If is there something broken please open a new PR.

**Pull request closed without merging**
